services:
  airflow-webserver:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse_proxy"

      - "traefik.http.routers.airflow.rule=Host(`airflow.cyberrabbit.it`)"
      - "traefik.http.routers.airflow.service=airflow"
      - "traefik.http.routers.airflow.entrypoints=tls"
      - "traefik.http.routers.airflow.tls=true"

      - "traefik.http.routers.airflow.middlewares=compresstraefik,airflow-securityheaders"

      - "traefik.http.services.airflow.loadbalancer.server.scheme=http"
      - "traefik.http.services.airflow.loadbalancer.server.port=8080"
      - "traefik.http.services.airflow.loadbalancer.passhostheader=true"

      - "traefik.http.middlewares.airflow-securityheaders.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.airflow-securityheaders.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.airflow-securityheaders.headers.stsPreload=true"
      - "traefik.http.middlewares.compresstraefik.compress=true"
    networks:
      - opencve

  airflow-scheduler:
    networks:
      - opencve

  airflow-worker:
    networks:
      - opencve

  airflow-init:
    command: !reset []
    networks:
      - opencve

  webserver:
    env_file: []
    networks:
      - opencve

  nginx:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse_proxy"

      - "traefik.http.routers.opencve.rule=Host(`opencve.cyberrabbit.it`)"
      - "traefik.http.routers.opencve.service=opencve"
      - "traefik.http.routers.opencve.entrypoints=tls"
      - "traefik.http.routers.opencve.tls=true"

      - "traefik.http.routers.opencve.middlewares=compresstraefik,opencve-securityheaders"

      - "traefik.http.services.opencve.loadbalancer.server.scheme=http"
      - "traefik.http.services.opencve.loadbalancer.server.port=80"
      - "traefik.http.services.opencve.loadbalancer.passhostheader=true"

      - "traefik.http.middlewares.opencve-securityheaders.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.opencve-securityheaders.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.opencve-securityheaders.headers.stsPreload=true"
      - "traefik.http.middlewares.compresstraefik.compress=true"

    networks:
      - opencve
      - reverse_proxy

  postgres:
    networks:
      - opencve

networks:
  opencve:
  reverse_proxy:
    external: true
